name: X-SetWarps
version: 1.4
main: com.fabian.xsetwarps.XSetWarps
api-version: 1.13
folia-supported: true
authors: [Fabian]
website: https://xproyects.qzz.io
description: "A simple setwarps plugin and customizable."
softdepend: [PlaceholderAPI, Essentials, CMI]

commands:
  xsetwarp:
    description: Main command for X-SetWarps
    aliases: [xsw]
    permission: xsetwarps.admin

permissions:
  xsetwarps.*:
    description: All permissions for X-SetWarps
    children:
      xsetwarps.admin: true
      xsetwarps.setwarp: true
      xsetwarps.warp: true
      xsetwarps.warp.*: true
      xsetwarps.delwarp: true
      xsetwarps.warps: true
      xsetwarps.warpgui: true
      xsetwarps.warpinfo: true
      xsetwarps.bypass-limit: true
      xsetwarps.bypass-cooldown: true
      xsetwarps.export: true
      xsetwarps.import: true
      xsetwarps.admin.forcemessages: true
  xsetwarps.admin:
    description: Permission to use admin commands
    default: op
    children:
      xsetwarps.setwarp: true
      xsetwarps.delwarp: true
      xsetwarps.warpinfo: true
      xsetwarps.warp.*: true
      xsetwarps.bypass-cooldown: true
      xsetwarps.export: true
      xsetwarps.import: true
      xsetwarps.admin.forcemessages: true
  xsetwarps.export:
    description: Permission to export warps
    default: op
  xsetwarps.import:
    description: Permission to import warps
    default: op
  xsetwarps.admin.forcemessages:
    description: Permission to use the forcemessages command
    default: op
  xsetwarps.setwarp:
    description: Permission to set warps
    default: op
  xsetwarps.warp:
    description: Permission to use basic warp command
    default: true
  xsetwarps.warp.*:
    description: Permission to use ALL warps
    default: op
  xsetwarps.delwarp:
    description: Permission to delete warps
    default: op
  xsetwarps.warps:
    description: Permission to list warps
    default: true
  xsetwarps.warpgui:
    description: Permission to open the warp GUI
    default: true
  xsetwarps.warpinfo:
    description: Permission to see warp info
    default: true
  xsetwarps.bypass-cooldown:
    description: Permission to bypass all warp cooldowns
    default: op
  xsetwarps.bypass-limit:
    description: Permission to bypass warp limit
    default: op